2022-08-20 00:11:45,118 DEBUG    root            Loaded Command Group: ['gcloud', 'services']
2022-08-20 00:11:45,122 DEBUG    root            Loaded Command Group: ['gcloud', 'services', 'enable']
2022-08-20 00:11:45,123 DEBUG    root            Running [gcloud.services.enable] with arguments: [--project: "cilium-20220820000618", SERVICE:3: "['compute.googleapis.com', 'container.googleapis.com', 'servicenetworking.googleapis.com']"]
2022-08-20 00:11:45,132 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): serviceusage.googleapis.com:443
2022-08-20 00:11:46,577 DEBUG    urllib3.connectionpool https://serviceusage.googleapis.com:443 "POST /v1/projects/cilium-20220820000618/services:batchEnable?alt=json HTTP/1.1" 400 None
2022-08-20 00:11:46,594 DEBUG    root            (gcloud.services.enable) FAILED_PRECONDITION: Billing account for project '266622789771' is not found. Billing must be enabled for activation of service(s) 'compute.googleapis.com,compute.googleapis.com,compute.googleapis.com,container.googleapis.com,container.googleapis.com,containerregistry.googleapis.com' to proceed.
Help Token: AfeSHlICt3D0a0ejDn1Q6ZfxAzqt0evgZmMg8bFHH7izfK42buyvmEVTM9UYLSlS4WuMXOa3_n8TfDtqNvx2_L2D_9LAve60t4ST2Q-rCA9rHb_b
- '@type': type.googleapis.com/google.rpc.PreconditionFailure
  violations:
  - subject: ?error_code=390001&project=266622789771&services=compute.googleapis.com&services=compute.googleapis.com&services=compute.googleapis.com&services=container.googleapis.com&services=container.googleapis.com&services=containerregistry.googleapis.com
    type: googleapis.com/billing-enabled
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: serviceusage.googleapis.com/billing-enabled
  metadata:
    project: '266622789771'
    services: compute.googleapis.com,compute.googleapis.com,compute.googleapis.com,container.googleapis.com,container.googleapis.com,containerregistry.googleapis.com
  reason: UREQ_PROJECT_BILLING_NOT_FOUND
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/surface/services/enable.py", line 94, in Run
    op = serviceusage.BatchEnableApiCall(project, args.service)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/api_lib/services/serviceusage.py", line 104, in BatchEnableApiCall
    return client.services.BatchEnable(request)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/third_party/apis/serviceusage/v1/serviceusage_v1_client.py", line 182, in BatchEnable
    return self._RunMethod(
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 737, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 743, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 609, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpBadRequestError: HttpError accessing <https://serviceusage.googleapis.com/v1/projects/cilium-20220820000618/services:batchEnable?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Fri, 19 Aug 2022 21:11:46 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'transfer-encoding': 'chunked', 'status': 400}>, content <{
  "error": {
    "code": 400,
    "message": "Billing account for project '266622789771' is not found. Billing must be enabled for activation of service(s) 'compute.googleapis.com,compute.googleapis.com,compute.googleapis.com,container.googleapis.com,container.googleapis.com,containerregistry.googleapis.com' to proceed.\nHelp Token: AfeSHlICt3D0a0ejDn1Q6ZfxAzqt0evgZmMg8bFHH7izfK42buyvmEVTM9UYLSlS4WuMXOa3_n8TfDtqNvx2_L2D_9LAve60t4ST2Q-rCA9rHb_b",
    "status": "FAILED_PRECONDITION",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
        "violations": [
          {
            "type": "googleapis.com/billing-enabled",
            "subject": "?error_code=390001&project=266622789771&services=compute.googleapis.com&services=compute.googleapis.com&services=compute.googleapis.com&services=container.googleapis.com&services=container.googleapis.com&services=containerregistry.googleapis.com"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "UREQ_PROJECT_BILLING_NOT_FOUND",
        "domain": "serviceusage.googleapis.com/billing-enabled",
        "metadata": {
          "project": "266622789771",
          "services": "compute.googleapis.com,compute.googleapis.com,compute.googleapis.com,container.googleapis.com,container.googleapis.com,containerregistry.googleapis.com"
        }
      }
    ]
  }
}
>
2022-08-20 00:11:46,597 ERROR    root            (gcloud.services.enable) FAILED_PRECONDITION: Billing account for project '266622789771' is not found. Billing must be enabled for activation of service(s) 'compute.googleapis.com,compute.googleapis.com,compute.googleapis.com,container.googleapis.com,container.googleapis.com,containerregistry.googleapis.com' to proceed.
Help Token: AfeSHlICt3D0a0ejDn1Q6ZfxAzqt0evgZmMg8bFHH7izfK42buyvmEVTM9UYLSlS4WuMXOa3_n8TfDtqNvx2_L2D_9LAve60t4ST2Q-rCA9rHb_b
- '@type': type.googleapis.com/google.rpc.PreconditionFailure
  violations:
  - subject: ?error_code=390001&project=266622789771&services=compute.googleapis.com&services=compute.googleapis.com&services=compute.googleapis.com&services=container.googleapis.com&services=container.googleapis.com&services=containerregistry.googleapis.com
    type: googleapis.com/billing-enabled
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: serviceusage.googleapis.com/billing-enabled
  metadata:
    project: '266622789771'
    services: compute.googleapis.com,compute.googleapis.com,compute.googleapis.com,container.googleapis.com,container.googleapis.com,containerregistry.googleapis.com
  reason: UREQ_PROJECT_BILLING_NOT_FOUND
